#!/bin/bash
source ../conf/config.sh

#echo "set names 'utf8';select dw_borrow_tender.user_id,card_id,dw_borrow.account,high_edu,repayment_time-verify_time,dw_area.name from dw_borrow_tender left join dw_user on dw_borrow_tender.user_id=dw_user.user_id left join dw_borrow on dw_borrow_tender.borrow_id=dw_borrow.id left join dw_area on dw_area.id=dw_user.province where dw_user.real_status=1"|$MYSQL|awk '{if(NR>1)print}'>info.txt
#echo "set names 'utf8';select dw_area.name,count(dw_area.name) from dw_borrow_tender left join dw_user on dw_borrow_tender.user_id=dw_user.user_id left join dw_area on dw_area.id=dw_user.province group by dw_area.name"|$MYSQL|awk '{if(NR>1)print}'|sort -k 2 -r>province.txt 
awk 'BEGIN{
    m_count=0;
    f_count=0;
    m_money=0;
    f_money=0;
    totalcount=0;
    totalmoney=0;
    age1_count=0;
    age2_count=0;
    age3_count=0;
    age4_count=0;
    age1_money=0;
    age2_money=0;
    age3_money=0;
    age4_money=0;
    edu_count=0;
    edu_money=0;
    highschool_count=0;
    techshcool_count=0;
    university_count=0;
    graduate_count=0;
    highschool_money=0;
    techshcool_money=0;
    university_money=0;
    graduate_money=0;
    year_now='`date +%Y`';
    m_three_count=0;
    m_six_count=0;
    m_twelve_count=0;
    m_twelve_more_count=0;
    f_three_count=0;
    f_six_count=0;
    f_twelve_count=0;
    f_twelve_more_count=0;
    age1_three_count=0;
    age1_six_count=0;
    age1_twelve_count=0;
    age1_twelve_more_count=0;
    age2_three_count=0;
    age2_six_count=0;
    age2_twelve_count=0;
    age2_twelve_more_count=0;
    age3_three_count=0;
    age3_six_count=0;
    age3_twelve_count=0;
    age3_twelve_more_count=0;
    age4_three_count=0;
    age4_six_count=0;
    age4_twelve_count=0;
    age4_twelve_more_count=0;
    highschool_six_count=0;
    highschool_three_count=0;
    highschool_twelve_count=0;
    highschool_twelve_more_count=0;
    techshcool_three_count=0;
    techshcool_six_count=0;
    techshcool_twelve_count=0;
    techshcool_twelve_more_count=0;
    university_three_count=0;
    university_six_count=0;
    university_twelve_count=0;
    university_twelve_more_count=0;
    graduate_three_count=0;
    graduate_six_count=0;
    graduate_twelve_count=0;
    graduate_twelve_more_count=0;
    province_count=0;
    province_money=0;
    p1_count=0;
    p2_count=0;
    p3_count=0;
    p4_count=0;
    p5_count=0;
    p1_money=0;
    p2_money=0;
    p3_money=0;
    p4_money=0;
    p5_money=0;
    p1_three_count=0;
    p1_six_count=0;
    p1_twelve_count=0;
    p1_twelve_more_count=0;
    p2_three_count=0;
    p2_six_count=0;
    p2_twelve_count=0;
    p2_twelve_more_count=0;
    p3_three_count=0;
    p3_six_count=0;
    p3_twelve_count=0;
    p3_twelve_more_count=0;
    p4_three_count=0;
    p4_six_count=0;
    p4_twelve_count=0;
    p4_twelve_more_count=0;
    p5_three_count=0;
    p5_six_count=0;
    p5_twelve_count=0;
    p5_twelve_more_count=0;
}{
    totalmoney+=$3;
    period=int($5/86400/31+0.5);
    sex_id=substr($2,17,1);
    p_id=substr($2,1,2);
    year=substr($2,7,4);
    age=year_now-year;
    if($1 in user){
        if(sex_id%2==1){
            m_money+=$3;}
        if(sex_id%2==0){
            f_money+=$3;}
        if(age<25){
            age1_money+=$3;}
        if(age>=25 && age<35){
            age2_money+=$3;}
        if(age>=35 && age<45){
            age3_money+=$3;}
        if(age>=45){
            age4_money+=$3;}
    }  
    else{
        user[$1]=1;
        totalcount++;
        if(sex_id%2==1){
            m_count++;
            m_money+=$3;
            if(period==3){
                m_three_count++;}
            if(period==6){
                m_six_count++;}
            if(period==9){
                m_twelve_count++;}
            if(period==12){
                m_twelve_more_count++;}
        }
        if(sex_id%2==0){
            f_count++;
            f_money+=$3;
            if(period==3){
                f_three_count++;}
            if(period==6){
                f_six_count++;}
            if(period==9){
                f_twelve_count++;}
            if(period==12){
                f_twelve_more_count++;}
        }
        if(age<25){
            age1_count++;
            age1_money+=$3;
            if(period==3){
                age1_three_count++;}
            if(period==6){
                age1_six_count++;}
            if(period==9){
                age1_twelve_count++;}
            if(period==12){
                age1_twelve_more_count++;}
        }
        if(age>=25 && age<35){
            age2_count++;
            age2_money+=$3;
            if(period==3){
                age2_three_count++;}
            if(period==6){
                age2_six_count++;}
            if(period==9){
                age2_twelve_count++;}
            if(period==12){
                age2_twelve_more_count++;}
        }
        if(age>=35 && age<45){
            age3_count++;
            age3_money+=$3;
            if(period==3){
                age3_three_count++;}
            if(period==6){
                age3_six_count++;}
            if(period==9){
                age3_twelve_count++;}
            if(period==12){
                age3_twelve_more_count++;}
        }
        if(age>=45){
            age4_count++;
            age4_money+=$3;
            if(period==3){
                age4_three_count++;}
            if(period==6){
                age4_six_count++;}
            if(period==9){
                age4_twelve_count++;}
            if(period==12){
                age4_twelve_more_count++;}
        }
        if($4!="NULL"){
            edu_count++;
            edu_money+=$3;
            if($4=="高中或以下"){
                highschool_count++;
                highschool_money+=$3;
                if(period==3){
                    highschool_three_count++;}
                if(period==6){
                    highschool_six_count++;}
                if(period==9){
                    highschool_twelve_count++;}
                if(period==12){
                    highschool_twelve_more_count++;}
            }
            if($4=="大专"){
                techschool_count++;
                techschool_money+=$3;
                if(period==3){
                    techschool_three_count++;}
                if(period==6){
                    techschool_six_count++;}
                if(period==9){
                    techschool_twelve_count++;}
                if(period==12){
                    techschool_twelve_more_count++;}
            }
            if($4=="本科"){
                university_count++;
                university_money+=$3;
                if(period==3){
                    university_three_count++;}
                if(period==6){
                    university_six_count++;}
                if(period==9){
                    university_twelve_count++;}
                if(period==12){
                    university_twelve_more_count++;}
            }
            if($4=="研究生或以上"){
                graduate_count++;
                graduate_money+=$3;
                if(period==3){
                    graduate_three_count++;}
                if(period==6){
                    graduate_six_count++;}
                if(period==9){
                    graduate_twelve_count++;}
                if(period==12){
                    graduate_twelve_more_count++;}
            }
        }
}}END{
    m_per=m_count/totalcount;
    f_per=f_count/totalcount;
    m_money_per=m_money/totalmoney;
    f_money_per=f_money/totalmoney;
    age1_per=age1_count/totalcount;
    age2_per=age2_count/totalcount;
    age3_per=age3_count/totalcount;
    age4_per=age4_count/totalcount;
    age1_money_per=age1_money/totalmoney;
    age2_money_per=age2_money/totalmoney;
    age3_money_per=age4_money/totalmoney;
    age4_money_per=age4_money/totalmoney;
    highschool_per=highschool_count/edu_count;
    techschool_per=techschool_count/edu_count;
    university_per=university_count/edu_count;
    graduate_per=graduate_count/edu_count;
    highschool_money_per=highschool_money/edu_money;
    techschool_money_per=techschool_money/edu_money;
    university_money_per=university_money/edu_money;
    graduate_money_per=graduate_money/edu_money;
    print totalcount,totalmoney,m_per,m_money_per,m_three_count,m_six_count,m_twelve_count,m_twelve_more_count,f_per,f_money_per,f_three_count,f_six_count,f_twelve_count,f_twelve_more_count,age1_per,age1_money_per,age1_three_count,age1_six_count,age1_twelve_count,age1_twelve_more_count,age2_per,age2_money_per,age2_three_count,age2_six_count,age2_twelve_count,age2_twelve_more_count,age3_per,age3_money_per,age3_three_count,age3_six_count,age3_twelve_count,age3_twelve_more_count,age4_per,age4_money_per,age4_three_count,age4_six_count,age4_twelve_count,age4_twelve_more_count,highschool_per,highschool_money_per,highschool_three_count,highschool_six_count,highschool_twelve_count,highschool_twelve_more_count,techschool_per,techschool_money_per,techschool_three_count,techschool_six_count,techschool_twelve_count,techschool_twelve_more_count,university_per,university_money_per,university_three_count,university_six_count,university_twelve_count,university_twelve_more_count,graduate_per,graduate_money_per,graduate_three_count,graduate_six_count,graduate_twelve_count,graduate_twelve_more_count,p1_per,p1_money_per,p1_three_count,p1_six_count,p1_twelve_count,p1_twelve_more_count,p2_per,p2_money_per,p2_three_count,p2_six_count,p2_twelve_count,p2_twelve_more_count,p3_per,p3_money_per,p3_three_count,p3_six_count,p3_twelve_count,p3_twelve_more_count,p4_per,p4_money_per,p4_three_count,p4_six_count,p4_twelve_count,p4_twelve_more_count,p5_per,p5_money_per,p5_three_count,p5_six_count,p5_twelve_count,p5_twelve_more_count}' info.txt
